import Navbar from "./components/navbar";
import Footer from "./components/footer";
import "./global.css";

export const metadata = {
  title: "Uwords AI",
  description: "Generated by Next.js",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="mainWrapper">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
